markdown: rdiscount
pygments: true
permalink: /docs/:title
domain: authenticatorplus.com
baseurl: http://authenticatorplus.com

title: Authenticator Plus
subtitle: Better way to manage 2-factor enabled accounts
author: Mufri
description: Authenticator Plus generates 2-step verficication codes which will protect your accounts with both your password and your phone / tablet. With Authenticator Plus you can seamlessly sync and manage all your 2-step enabled accounts in phones / tablet / kindle.
google_analytics_tracking_id: UA-44491916-3
